### PR TITLE
Make the project compatible with Ember 1.13 and 2.2

### PR DESCRIPTION
**Pull request by diogomafra**
This PR is not finished, I just want to get some feedback.

There are a few required changes to make the project compatible with Ember 1.13:

- The property names must be quoted (`{{input "name"}`).
- Rename the `input` helper to `input-for`. I could not find a way to override Ember's helper (actually, it's a HTMLBar's keyword). I can try again, but I think it's better to avoid name collisions.
- The `select` view was deprecated on Ember 1.13 and removed on 2.0. We should not use it. Instead, we can provide another addon or a sample code showing how to create a input for a select component.
- It was possible to use a property outside the model in the input helper (`{{input controller.someProperty}}`). The code relies on the names "controller" and "view", that are deprecated and don't work on Ember 2.0. I'm not sure what are the use-cases for this, maybe we can remove the support for this? 

What are your thoughts @bcardarella ?

### CODE REVIEW

**Comment by bcardarella** [comment]
> The property names must be quoted ({{input "name"}).

Confirm

> Rename the input helper to input-for. I could not find a way to override Ember's helper (actually, it's a HTMLBar's keyword). I can try again, but I think it's better to avoid name collisions.

This should be OK for the purposes of the compatibility version this is providing. We're going to re-write this project for its 2.0 release and use some new stuff coming out in Ember 2.3 to get the proper component names.

> The select view was deprecated on Ember 1.13 and removed on 2.0. We should not use it. Instead, we can provide another addon or a sample code showing how to create a input for a select component.

Confirm. I would prefer to leave this open-ended so other select implementations can be plugged in. There are a few out there at this point.

> It was possible to use a property outside the model in the input helper ({{input controller.someProperty}}). The code relies on the names "controller" and "view", that are deprecated and don't work on Ember 2.0. I'm not sure what are the use-cases for this, maybe we can remove the support for this?

Views are now "private" in Ember 2.x. Controllers are still public because routable components didn't make the cut.

**Comment by diogomafra** [comment]
After a long time, in a galaxy far, far away, I finally finished this PR :smiley:.

I think all required changes are done. It's working with Ember 1.13, 2.2 and 2.3. I would love if more people could test it in some real projects.

Here is the changelog:

  * This library now supports Ember 1.13 and Ember 2.\*.
  * The `input` helper was renamed to `input-for`, and now it's a component.
  * The property name passed to the `input-for` component must be quoted (e.g. `{{input-for "name"}}`).
  * Previously, to use dynamic values it was necessary to use the `Binding` suffix (`{{input-for "name" placeholderBinding="someProperty"}}`). Now it's possible to use bindings without the suffix (`{{input-for "name" placeholder=someProperty}}`).
  * The support for internationalization was removed. Previously it was possible to use the `Translation` suffix (`{{input-for "firstName" labelTranslation="some-translation-key"}}`). Now you can use the i18n helper of your library of choice (`{{input-for "firstName" label=(t "some-translation-key")}}`).
  * The `select` view was deprecated on Ember 1.13 and removed on Ember 2.0. To support both versions we had to remove the direct support for it. You can define a custom input helper using any select component you want.
  * Previously, to use a property defined in the controller in the `input-for` helper, you had to define the property name with the suffix "controller.". Now you can define the `value` property of the `input-for` (`{{input-for "someProperty" value=somePropertyInTheControllerOrComponent}}`).
  * The `hint-field` component does not hide itself when the text is empty.
    Previously it was a helper that didn't render with an empty text. If you use it inside the block form of the `input-for` component, you have to remember to render it only when there is a text (`{{#if hintText}}{{hint-field ...}}{{/if}}`).
  * The name of some component templates changed. If you override the default templates, check their new names.
  * The content of all component templates changed. If you have custom templates, check the new templates.

**Comment by bcardarella** [comment]
ZOMG

:tada: :heart:

**Comment by diogomafra** [comment]
:heart: :heart: :heart: 

Now we need to publish the NPM package and ask for more testers.

**Comment by diogomafra** [comment]
There are many old issues that can be closed now. I’d like to make a triage, if that’s ok to you.

**Comment by bcardarella** [comment]
@diogomafra yes please do :smile:

**Comment by piotrze** [comment]
@diogomafra Is this gonna work with ember-validations 2.0?

**Comment by diogomafra** [comment]
@piotrze I don't know. I'm not following the development of ember-validations.

**Comment by piotrze** [comment]
@diogomafra Thanks for this PR it really helped with migrating to ember 1.13.13 :)

**Pull request merged**
