### PR TITLE
Convert the project to Ember-cli

### PR DESCRIPTION
**Pull request by diogomafra**
This PR converts the project to use Ember-cli. I kept as much as possible of the original code, just moving around the code.

The project is not compatible with Ember 1.13 yet, I will submit another PR updating the Ember version.

This PR is not ready to be merged. A few pending changes:
- [x] `Ember.meta().descs` doesn't exist anymore (https://github.com/emberjs/ember.js/pull/10323)
- [ ] ~~Load Ember.i18n using modules instead of globals~~
- [ ] ~~Tests with `input[type=date]` and `input[type=time]` don't work on PhantomJS~~
- [x] Update the readme

### CODE REVIEW

**Comment by diogomafra** [comment]
There are two pending changes, but I think we can keep them as is.

The first one is changing how we get the translations. I'm not familiar with all use cases, and I prefer not having to deal with it at the moment. Who wants to use this feature can define the global object `Ember.i18n`. We can also change it later.

The second pending change is enabling some tests that are failing on PhantomJS. For some reason input fields with the type `date` or `time` are created as `text`. I think it's because PhantomJS is using an old version of WebKit, or some bug in Ember 1.12.

What do you think @bcardarella? Let's merge this and deal with the pending changes in another PR?

**Comment by bcardarella** [comment]
:+1: can you consolidate into a single commit?

**Comment by diogomafra** [comment]
Done!

**Comment by bcardarella** [comment]
@diogomafra what version of phantomjs are you using?

**Comment by diogomafra** [comment]
2.0

**Comment by bcardarella** [comment]
According to http://caniuse.com/#search=date `date` & `time` aren't supported in Safari at all. Same goes for Firefox and IE 11. I would prefer to skip the tests rather than comment them out: https://api.qunitjs.com/QUnit.skip/

**Comment by diogomafra** [comment]
Oops, I don't know why I didn't use the `skip` method. I forgot that method exists. :)

**Comment by diogomafra** [comment]
Done, I updated the tests to use `skip`.

**Comment by bcardarella** [comment]
Awesome, thank you! :smile:

**Pull request merged**
